### 1 Login REST para obtener el token
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "erick@rock.com",
  "password": "password123"
}

### 2 Variable de token a partir de la respuesta
@token = {{login.response.body.accessToken}}


### 3 get Schemas
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "query": "query { __schema { queryType { fields { name } } } }"
}

### 3 get External
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "query": "query { externalDashboard { coffees { title } beers { name } characters { name } } }"
}
