### Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "erick@rock.com",
  "password": "password123"
}

### Token
@token = {{login.response.body.accessToken}}

### Get ME
GET http://localhost:3000/auth/me
Authorization: Bearer {{token}}


### Create project
POST http://localhost:3000/projects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Marta & Erick",
  "description": "First project managed by our Dublín"
}

### Cambiar owner del proyecto 1 al usuario 2
PATCH http://localhost:3000/projects/4/owner
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 2
}

### Get all projects
GET http://localhost:3000/projects
Authorization: Bearer {{token}}

### Get project By Id
GET http://localhost:3000/projects/1
Authorization: Bearer {{token}}

### Update project By Id
PATCH http://localhost:3000/projects/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Updated Dublin"
}

### Delete project By Id
DELETE http://localhost:3000/projects/1
Authorization: Bearer {{token}}

